name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      # TODO build and run unit tests DONE
      - name: set up JDK 19
        uses: actions/setup-java@v1
        with:
            java-version: 19
            distribution: 'adopt'
#      - name: Maven Package
#        run: mvn -B clean package

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.1
          
      - name: Build RatingService to jar
        run: mvn -f lab2/RatingService/pom.xml --batch-mode --update-snapshots clean package -DskipTests
      - name: Build LibraryService to jar
        run: mvn -f lab2/LibraryService/pom.xml --batch-mode --update-snapshots clean package -DskipTests
      - name: Build ReservationService to jar
        run: mvn -f lab2/ReservationService/pom.xml --batch-mode --update-snapshots clean package -DskipTests
      - name: Build Gateway to jar
        run: mvn -f lab2/Gateway/pom.xml --batch-mode --update-snapshots clean package -DskipTests

      - name: Build images
        timeout-minutes: 10
        run: docker compose build

      - name: Run containers
        timeout-minutes: 5
        run: |
          docker compose up -d
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050

      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          # TODO insert your variant
          collection: v4/postman/collection.json
          environment: v4/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 2
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v